import type { Metadata } from "next";
import {Chakra_Petch} from "next/font/google"
import "../styles/globals.css";
import Cursor from "../components/cursor";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const chakraPetch = Chakra_Petch({
  weight: "400",
  subsets: ["latin"]
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={chakraPetch.className}>
        <Cursor />
        {children}
        <Navbar />
      </body>
    </html>
  );
}
