import type { Metadata } from "next";
import {Itim} from "next/font/google"
import "../styles/globals.css";
import Cursor from "../components/cursor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const itim = Itim({
  weight: "400",
  subsets: ["latin"]
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={itim.className}>
        <Cursor />
        {children}
      </body>
    </html>
  );
}
